In [72]:
import requests
import pandas as pd
import datetime as dt

In [128]:
PARAMS = {
#DOCUMENTATION USED: https://www.weatherbit.io/api/weather-forecast-120-hour  
    
#Get forecast by lat/lon 	lat,lon
    'lat':12.92735,
    'lon':77.67185,
    
#Get forecast by city name  	city, state(optional), country (optional)
    
#Get forecast by postal code 	postal_code, country (optional)
#     'postal_code': 560102,
#     'country': 'IN',
    
#Get forecast by Station 	station
    
#Get forecast by city id 	city_id
    
    'lang':'en',
    'hours':48 
}


r = requests.get("https://weatherbit-v1-mashape.p.rapidapi.com/forecast/hourly",
                 headers={
                     "X-RapidAPI-Host": "weatherbit-v1-mashape.p.rapidapi.com",
                     "X-RapidAPI-Key": "9760fa76cemsh3b3bc0cfd34ff97p14b793jsnacc85f71e316"
                 },
                 params = PARAMS
)

r

r.text

In [130]:
data = json.loads(r.text)

data

In [132]:
from pandas.io.json import json_normalize
weather_forecast = json_normalize(data['data'])

In [133]:
weather_forecast['datetime'] = pd.to_datetime(weather_forecast['datetime'], format = "%Y-%m-%d:%H")
weather_forecast['timestamp_local'] = pd.to_datetime(weather_forecast['timestamp_local'])
weather_forecast['city'] = data['city_name']
weather_forecast['lon'] = data['lon']
weather_forecast['lat'] = data['lat']

In [142]:
weather_codes = pd.read_csv("weather_codes.csv")
weather_codes.drop(labels='Description ',axis = 1, inplace = True)
weather_codes = dict(zip(weather_codes['Code '], weather_codes.Weather))
#Makes dictionary to access values

In [140]:
weather_forecast['weather_code'] = weather_forecast['weather.code'].apply(lambda x : int(weather_codes[x]))

In [141]:
weather_forecast[['lat', 'lon', 'city','app_temp', 'datetime', 'timestamp_local', 'temp', 'rh', 'wind_spd', 'weather_code']]

,lat,lon,city,app_temp,datetime,timestamp_local,temp,rh,wind_spd,weather_code
0,13.0907,77.6423,Bangalore,29.8,2019-07-18 11:00:00,2019-07-18 16:30:00,28.6,55,4.87335,2
1,13.0907,77.6423,Bangalore,28.4,2019-07-18 12:00:00,2019-07-18 17:30:00,27.2,61,4.65423,3
2,13.0907,77.6423,Bangalore,26.4,2019-07-18 13:00:00,2019-07-18 18:30:00,26.0,68,3.96667,3
3,13.0907,77.6423,Bangalore,26.0,2019-07-18 14:00:00,2019-07-18 19:30:00,25.6,70,4.55840,4
4,13.0907,77.6423,Bangalore,25.4,2019-07-18 15:00:00,2019-07-18 20:30:00,25.0,72,4.56597,4
5,13.0907,77.6423,Bangalore,25.1,2019-07-18 16:00:00,2019-07-18 21:30:00,24.6,74,4.71965,4
6,13.0907,77.6423,Bangalore,24.5,2019-07-18 17:00:00,2019-07-18 22:30:00,24.0,78,4.15162,4
7,13.0907,77.6423,Bangalore,23.9,2019-07-18 18:00:00,2019-07-18 23:30:00,23.4,80,4.94100,4
8,13.0907,77.6423,Bangalore,23.3,2019-07-18 19:00:00,2019-07-19 00:30:00,22.7,84,5.15477,4
9,13.0907,77.6423,Bangalore,22.5,2019-07-18 20:00:00,2019-07-19 01:30:00,21.9,89,5.91622,4
10,13.0907,77.6423,Bangalore,22.1,2019-07-18 21:00:00,2019-07-19 02:30:00,21.6,90,6.78754,4
11,13.0907,77.6423,Bangalore,22.1,2019-07-18 22:00:00,2019-07-19 03:30:00,21.6,89,6.19908,4
12,13.0907,77.6423,Bangalore,21.9,2019-07-18 23:00:00,2019-07-19 04:30:00,21.4,88,5.42197,4
13,13.0907,77.6423,Bangalore,21.7,2019-07-19 00:00:00,2019-07-19 05:30:00,21.2,89,5.44435,4
14,13.0907,77.6423,Bangalore,21.6,2019-07-19 01:00:00,2019-07-19 06:30:00,21.1,89,5.22753,4
15,13.0907,77.6423,Bangalore,21.6,2019-07-19 02:00:00,2019-07-19 07:30:00,21.1,89,4.85325,4
16,13.0907,77.6423,Bangalore,21.6,2019-07-19 03:00:00,2019-07-19 08:30:00,21.1,89,4.74433,4
17,13.0907,77.6423,Bangalore,21.6,2019-07-19 04:00:00,2019-07-19 09:30:00,21.1,90,4.23397,3
18,13.0907,77.6423,Bangalore,21.9,2019-07-19 05:00:00,2019-07-19 10:30:00,21.4,88,3.81254,2
19,13.0907,77.6423,Bangalore,22.4,2019-07-19 06:00:00,2019-07-19 11:30:00,21.9,86,3.42732,1
20,13.0907,77.6423,Bangalore,23.1,2019-07-19 07:00:00,2019-07-19 12:30:00,22.6,84,3.68802,1
21,13.0907,77.6423,Bangalore,23.4,2019-07-19 08:00:00,2019-07-19 13:30:00,22.9,82,4.05710,1
22,13.0907,77.6423,Bangalore,23.9,2019-07-19 09:00:00,2019-07-19 14:30:00,23.4,80,4.25885,1
23,13.0907,77.6423,Bangalore,24.3,2019-07-19 10:00:00,2019-07-19 15:30:00,23.9,78,4.29415,1
24,13.0907,77.6423,Bangalore,24.2,2019-07-19 11:00:00,2019-07-19 16:30:00,23.7,77,4.31418,1
25,13.0907,77.6423,Bangalore,24.1,2019-07-19 12:00:00,2019-07-19 17:30:00,23.6,77,3.84191,1
26,13.0907,77.6423,Bangalore,23.7,2019-07-19 13:00:00,2019-07-19 18:30:00,23.3,79,3.23379,1
27,13.0907,77.6423,Bangalore,23.2,2019-07-19 14:00:00,2019-07-19 19:30:00,22.8,80,3.34185,1
28,13.0907,77.6423,Bangalore,22.9,2019-07-19 15:00:00,2019-07-19 20:30:00,22.5,80,3.22429,1
29,13.0907,77.6423,Bangalore,22.9,2019-07-19 16:00:00,2019-07-19 21:30:00,22.5,78,2.97357,1
30,13.0907,77.6423,Bangalore,22.9,2019-07-19 17:00:00,2019-07-19 22:30:00,22.5,77,3.29765,1
31,13.0907,77.6423,Bangalore,22.7,2019-07-19 18:00:00,2019-07-19 23:30:00,22.3,78,3.64631,1
32,13.0907,77.6423,Bangalore,22.4,2019-07-19 19:00:00,2019-07-20 00:30:00,22.1,82,4.13572,1
33,13.0907,77.6423,Bangalore,22.3,2019-07-19 20:00:00,2019-07-20 01:30:00,21.8,85,4.69462,1
34,13.0907,77.6423,Bangalore,22.0,2019-07-19 21:00:00,2019-07-20 02:30:00,21.5,86,5.26466,1
35,13.0907,77.6423,Bangalore,21.8,2019-07-19 22:00:00,2019-07-20 03:30:00,21.3,86,5.24377,1
36,13.0907,77.6423,Bangalore,21.7,2019-07-19 23:00:00,2019-07-20 04:30:00,21.2,87,5.13060,1
37,13.0907,77.6423,Bangalore,21.5,2019-07-20 00:00:00,2019-07-20 05:30:00,21.1,87,4.73828,1
38,13.0907,77.6423,Bangalore,21.5,2019-07-20 01:00:00,2019-07-20 06:30:00,21.1,87,4.43129,1
39,13.0907,77.6423,Bangalore,21.8,2019-07-20 02:00:00,2019-07-20 07:30:00,21.4,86,4.45342,1
40,13.0907,77.6423,Bangalore,22.6,2019-07-20 03:00:00,2019-07-20 08:30:00,22.1,82,4.87095,1
41,13.0907,77.6423,Bangalore,24.1,2019-07-20 04:00:00,2019-07-20 09:30:00,23.7,76,5.30424,1
42,13.0907,77.6423,Bangalore,24.3,2019-07-20 05:00:00,2019-07-20 10:30:00,23.9,75,5.37597,1
43,13.0907,77.6423,Bangalore,25.6,2019-07-20 06:00:00,2019-07-20 11:30:00,25.1,70,6.08447,1
44,13.0907,77.6423,Bangalore,26.9,2019-07-20 07:00:00,2019-07-20 12:30:00,26.5,64,6.93835,1
45,13.0907,77.6423,Bangalore,28.1,2019-07-20 08:00:00,2019-07-20 13:30:00,26.9,61,7.97869,1
46,13.0907,77.6423,Bangalore,26.5,2019-07-20 09:00:00,2019-07-20 14:30:00,26.1,64,7.41774,1
47,13.0907,77.6423,Bangalore,26.8,2019-07-20 10:00:00,2019-07-20 15:30:00,26.4,62,7.56171,1